#!/usr/bin/env ruby

class HVMCodeGen
  attr_reader :code
  def initialize
    @code = ""
  end

  def push(c)
    @code << c
  end

  def dup
    push "0^"
  end

  def push_number(n)
    if n <= 9
      @code << n.to_s
    else
      d = n / 9
      r = n % 9
      if d == 1
        push "9"
      else
        push_number(d)
        push "9*"
      end
      if r != 0
        push "#{r}+"
      end
    end
  end

  def print_char(c)
    push_number c.ord
    push "P "
  end

  def print_str(s)
    s.split(//).each do |c|
      print_char(c)
    end
  end

  def load_mem(i)
    push_number(i)
    push "<"
  end

  def save_mem(i)
    push_number(i)
    push ">"
  end

  def king_rat_step(i)
    load_mem i
    push_number (i+1)

    load_mem i
    load_mem (i+1)
    push ":"
    push_number 1
    push ":"
    push "1+"
    push "1?"
    push ">"
  end

  def king_rat
    (0..18).each do |i|
      king_rat_step(i)
    end
    load_mem 19
    push "p"
  end

  def shift_right_one_bit(i)
    load_mem(i)   # a
    dup           # a a
    push "2/"     # a (a/2)
    dup           # a (a/2) (a/2)
    save_mem(i)   # a (a/2)
    push "2*"     # a (a/2*2)
    push "-"      # a[0]
  end

  def xor
    push "0"
    push "1"
    # 2:
    shift_right_one_bit(0)
    shift_right_one_bit(1)
    push "0"   # x y 0
    push "1^"  # x y 0 y
    push "3^"  # x y 0 y x
    push "2**" # x y 0 (y*x*2)
    push "-"   # x y (-2*y*x)
    push "++"  # (x+y-2*y*x)

    push "1^*"   # sum, pow2, part
    push "2v+"   # pow2, sum+part
    push "1v0^+" # sum+part, pow2*2
  end

  def find_dups(num=12)
    (0...num).each do |i|
      (i+1..num).each do |j|
        load_mem i
        dup
        load_mem j
        push "-"
        push "2?2g"
        push "p!"
      end
    end
  end

  def broken_key
    load_mem 0
    load_mem 1
    push "/"
    push "4?"
    push "0<p!"
    push "1<p"
  end

  def broken_keys
    # (1/((a+b)/b))*b + (1/((a+b-1)/a))*a
    push "1"
    load_mem 0
    load_mem 1
    push "+"      # 1, (a+b)
    load_mem 1
    push "/"      # 1, (a+b)/b
    push "/"      # (1/((a+b)/b))
    load_mem 1
    push "*"      # (1/((a+b)/b))*b

    push "1"
    load_mem 0
    load_mem 1
    push "+"
    push "1-"     # 1, (a+b-1)
    load_mem 0
    push "/"      # 1, (a+b-1)/b
    push "/"      # (1/((a+b-1)/a))
    load_mem 0
    push "*"      # (1/((a+b-1)/b))*a

    push "+p"
  end

  def brokener_keys
    load_mem 0
    load_mem 1
    push "888**0<1<--4*c"
    (0..255).each do |a|
      (0..255).each do |b|
        addr = (4*(512+b-a))
        # puts [addr, a <=> b].join(' ')
        @code += " " while @code.size < addr
        if a > b
          @code[addr, 4] = "0<p!" if a==255 and b == 254
        else
          @code[addr, 4] = "1<p!" if b==255 and a == 0
        end
      end
    end
  end

  def overflow_minus_one
    push_number(2**32-1)
  end

  def brokenest_keys
    push "0"
    push "0^1+" * 256
    push "0<^"
    push "1<+4*"
    push_number 1200
    push "+c"
    (0..255).each do |a|
      (0..255).each do |b|
        addr = 1200 + 4*(256+b-a)
        # puts [addr, a <=> b].join(' ')
        @code += " " while @code.size < addr
        if a > b
          @code[addr, 8] = "0<p!" if a==255 and b == 254
        else
          @code[addr, 8] = "1<p!" if b==255 and a == 0
        end
      end
    end
  end

  def deja_vu
    push_number 127
    raise unless @code.size == 7
    # LoopA:
    push "0"      # STACK: counterA, coutnerB

    raise unless @code.size == 8
    # LoopB
    push "0^<"    # STACK: counterA, counterB, [B]
    push "2^<"    # STACK: counterA, counterB, [B] [A]
    push ":"      # STACK: counterA, counterB, [B]<=>[A]
    push "2?5g"   # if [A] != [B] jump to X:
    push "0^<p!"  # if found dup, print it and quit

    # X:
    push "1+"     # counterB += 1
    push "0^2^:"  # STACK:counterA, coutnerB, counterA<=>coutnerB

    push "2?"
    push "8c"     # if counterB < counterA goto LoopB

    push "d"      # STACK: counterA
    push "1-"     # counterA -= 1
    push "7c"     # goto loopA

    # do fun stuff
  end

  def king_mouse
    push "0"
    raise unless @code.size == 1
    push "0^1+"  # A, A+1
    push "1^<"   # A, A+1, [A]
    push "1^<"   # A, A+1, [A], [A+1]
    push ":"     # A, A+1, [A]<=>[A+1]
    push "1+6?"  # jump forward if second already greater
    push "1^<1^" # A, A+1, [A], A+1
    push ">"     # mem[A+1] = mem[A]
    push "0^45*/3?" # jump forward if A == 20
    push "<p!"
    push "1c"
    warn "Code size is: #{@code.size}"
  end
end

codegen = HVMCodeGen.new
# codegen.print_str "Hello, World"
codegen.king_mouse
puts codegen.code
